### ISSUE TITLE
impossible to install

### ISSUE THREAD

**Issue by fcodebue** [Eddie84/facebook-event-plugin#1]
I download your plugin. zip it in plug_fb_events_pro.zip and try to install
Joomla tell to me

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

some idea?

**Comment by Eddie84** [comment]
I've a new installation of Joomla, I've downloaded the zip directly from github then tried to install and it work fine.
